### ISSUE TITLE
802.11a/an-only AP are not supported

### ISSUE THREAD

**Issue by dguerri** [openwisp/OpenWISP-Firmware#12]
Access points with only 5Ghz radios are not supported because OWF forces the use of channel 1 (i.e. 2,412Ghz) for the setup services:

https://github.com/openwisp/OpenWISP-Firmware/blob/master/tools/mac80211.sh#L71
https://github.com/openwisp/OpenWISP-Firmware/blob/master/owispmanager.sh#L305

If we're using mac80211 driver we can use something like the following in order to determine the first available channel:

```bash
iw phy0 info | awk 'BEGIN { FS="[\]|\[]" } ; /Frequencies/ { getline; print $2 }'
```

The output on a Nanostation M2:

```bash
~# iw phy0 info | awk 'BEGIN { FS="[\]|\[]" } ; /Frequencies/ { getline; print $2 }'
1
```

**Comment by claudyus** [comment]
is now in master after commit https://github.com/openwisp/OpenWISP-Firmware/commit/0ef1abbe54947ca2d51940902016933317b35481 (wrong description in commit)
