### ISSUE TITLE
Restoration of unifi ap outdoor after unsuccessful flashing.

### ISSUE THREAD

**Issue by sanekxpmail** [openwisp/OpenWISP-Firmware#18]
After a failed firmware, the device stops responding SSSH.
Through a Web interface provides:
This device has been identified as counterfeit.
AirOS is not licensed for use on this device and has been disabled.
Please see the Ubiquiti Brand Protection page at www.ubnt.com
for more information.

Due to the lack of visual images in the article: https://github.com/openwisp/OpenWISP-Firmware/wiki/Unifi
I am not able to fully understand how to reflash. It was possible to do the following, disassemble the unit, take the USB cable is connected to the TTL and PC.
Cable usb to TTL, used a custom cable for the mouse, pinout connecting was standard red, green, white, black.
After putty introduced parameters 115200-8N1 com1/com2/usb1/usb2 port, but to join the device did not work.

I ask you to help deal with the flashing the device. Write a statement or make recommendations as possible pereproshivt device using the operating system windows 7.

**Comment by nemesisdesign** [comment]
unifi ap outdoor is supported in the 1.3 release
