### ISSUE TITLE
fatal: No names found, cannot describe anything

### ISSUE THREAD

**Issue by urako** [openwisp/OpenWISP-Firmware#26]
All of openwrt installs well just having issues with this. missing tags?

fatal: No names found, cannot describe anything.
Package: openwisp-fw-base
Version:

**Comment by urako** [comment]
Managed to get past that with changing

PKG_VERSION:=$(shell git describe –tags)
to
PKG_VERSION:=1.3 alpha

in feeds/openwisp/meta/openwisp-fw/Makefile
and running 

./scripts/feeds update -a
again

Is there any way to prevent this?

**Comment by vilpalu** [comment]
fork own copy and change it.

**Comment by nemesisdesign** [comment]
@urako thank you for telling us, we'll look into it @claudyus @cvalenti @riblo

**Comment by urako** [comment]
:+1:

**Comment by urako** [comment]
Still have this one aswell 

>fatal: No tags can describe 'ada6e16203c0a17ff700fb3651ec8cc79c4fa3c7'

Do not know how to tag that

**Comment by claudyus** [comment]
We can fallback in using a fixed string like:
```
PKG_VERSION:=$(git describe --tags 2> /dev/null || echo no-git) # just an example
```
or save a release file somewhere and remember to update it during release phase:
```
PKG_VERSION:=$(git describe --tags 2> /dev/null || cat some_where_version_file)
```

I'm anyway against a fixed PKG_VERSION that doesn't follow the git progress.

**Comment by urako** [comment]
Tried your example

>PKG_VERSION:=$(git describe --tags 2> /dev/null || echo no-git) # just an example

same result


I have also tried 
>..openwrt$ git describe --always
>ada6e1

as suggested by 

>fatal: No tags can describe 'ada6e16203c0a17ff700fb3651ec8cc79c4fa3c7'.
>Try --always, or create some tags.

but still in 

>logs/package/feeds/openwisp/openwisp-fw/dump.txt

there is

>Makefile:100: *** Package/openwisp-fw-base is missing the VERSION field.  Stop.

**Comment by urako** [comment]
>git tag 1.3-alpha-38-gada6e16 ada6e16

solved it for me now, and able to compile the bins, yaay!
