### ISSUE TITLE
recheck owispmanager options usage

### ISSUE THREAD

**Issue by cappe87** [openwisp/OpenWISP-Firmware#30]
option 'ethernet_enable' '0'

 this option disable eth by default?

**Comment by claudyus** [comment]
this option was introduced in https://github.com/openwisp/OpenWISP-Firmware/commit/d6ea7c2bc but is not referenced anywhere else and could be removed

**Comment by claudyus** [comment]
I will reopen this just to remember to cleanup the config file and docs by old config options

**Comment by cappe87** [comment]
whit this
root:$1$SwrPpeIH$8MMk3YQiVXl5uQzRgTIvU/:16386:0:99999:7:::
daemon:*:0:0:99999:7:::
ftp:*:0:0:99999:7:::
network:*:0:0:99999:7:::
nobody:*:0:0:99999:7:::


root's password isn't pass
doesn't work

**Comment by claudyus** [comment]
@cappe87 the root pass problem is another issue from the original topic, you should open another ticket for it and not reuse an old one :)

**Comment by claudyus** [comment]
still reopened because none of two issues are solved :-D

**Comment by riblo** [comment]
Closed by cd956d3
