### ISSUE TITLE
Stop compilation if $OPENWISP_CONF var is not valid

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/OpenWISP-Firmware#37]
This block:
https://github.com/openwisp/OpenWISP-Firmware/blob/master/meta/openwisp-fw/Makefile#L71-L88

should abort in case the content of `$OPENWISP_CONF` is not valid (not a folder, not a file, not a URL) and display a human readable error message.

**Comment by nemesisdesign** [comment]
Can we merge and issue a new release? It seems someone else got burned by this issue, see #41.
The sooner we release this, the better (less time spent debugging issues).

**Comment by claudyus** [comment]
If this is a "bug" we could release it in 1.3.xyz release otherwise if this is and "enhancement" for 1.4 we should release this inside the next minor.
