### ISSUE TITLE
wireless n mode doesn't work

### ISSUE THREAD

**Issue by cappe87** [openwisp/OpenWISP-Firmware#40]
I select ng mode in the template but wireless works only in g mode.
I think the problem is in the file /etc/owispmanager/tools/mac80211.sh at line 47
echo "hw_mode=g" >> $HOSTAPD_FILE
This probably rewrites the configuration in owm.

**Comment by nemesisdesign** [comment]
Sounds like a problem in OWM rather than the firmware.

**Comment by nemesisdesign** [comment]
Looking at the UCI of OWM, I think n just cannot work:
https://github.com/openwisp/OpenWISP-Manager/blob/master/app/views/access_points/_uci_wireless_mac80211.erb

An example of correct 802.11n settings for 2ghz are here:
https://github.com/openwisp/netjsonconfig/blob/master/tests/openwrt/test_wireless.py#L90-L91

Or for 5ghz:
https://github.com/openwisp/netjsonconfig/blob/master/tests/openwrt/test_wireless.py#L55-L56

**Comment by nemesisdesign** [comment]
Hey @cappe87, I just tested the current master with a correct 802.11n configuration generated via [netjsonconfig](https://github.com/openwisp/netjsonconfig) and the access point correctly sets itself in 802.11n mode.

This unfortunately is a limit of OpenWISP Manager which generates a wrong configuration. We have a solution for this, get in touch and I will help.
