### ISSUE TITLE
Kernel panic on Ubiquiti Unifi AP

### ISSUE THREAD

**Issue by ntt1985** [openwisp/OpenWISP-Firmware#41]
Hi, I'm trying to compile openwisp firmware using openwrt 15.05 for Ubiquiti UniFi AP (LR). I'm using the squashfs-factory.bin image and compilation goes well. When I load the firmware on the board (with tftp) and I connect the pppoe to the internet, I have a kernel panic with message:
"CPU0 Unable to handle kernel paging request at virtual address ......"
Same behavior if I use the jffs2 image.
Someone can help me please?

Edit: the problem happens also if I dont connect the board to the internet
Thank you

**Comment by nemesisdesign** [comment]
I never experienced this issue and I have no idea. If neither @riblo nor @claudyus can give a useful suggestion, I would suggest to look on the OpenWRT bug tracker if anyone else is experiencing a similar issue.

**Comment by ntt1985** [comment]
Ok... more details and an apparently resolution:
I think the problem was related to missing .tar.gz configuration tree. I think I forget "export ..." before make. Anyway, this model, UniFi AP LR  (ar7241) is unsupported in trunk but works in 15.05 and 14.07 because it has a particular firmware header (BZ instead XM). Furthermore it is impossible compile older version because luci repo is down for version 12.09 and below. Actually I compiled the firmware with version 15.05 and it seems to be stable.
Let me know a thing: the Ap automatically reboot itself if the service vpn is not connected?
Thank you for support.

**Comment by nemesisdesign** [comment]
There's a reboot feature but it's not enabled by default, see https://github.com/openwisp/OpenWISP-Firmware/blob/master/meta/openwisp-fw/files/etc/config/owispmanager#L22-L24

**Comment by ntt1985** [comment]
Ok, thank you. I can consider the issue as closed. 
PS: How can I enable that feature? Should I set manually to '1' the flag in the configuration file?

**Comment by nemesisdesign** [comment]
@ntt1985 yes
