### ISSUE TITLE
Compilation Fail

### ISSUE THREAD

**Issue by boryss** [openwisp/OpenWISP-Firmware#42]
Hello,

for the past few days i've had a bit trouble with compiling openwrt. No matter what i do i get the same issue and i can't seem to understand what did i do wrong. I have tryed compiling different openwrt versions but i get always the same result.

This is the output of the compilation:

make[3]: *** [/home/borys/openwrt/bin/x86/packages/openwisp/openwisp-fw-base_7987c89_x86.ipk] Error 2
make[3]: Leaving directory `/home/borys/openwrt/feeds/openwisp/meta/openwisp-fw'
make[2]: *** [package/feeds/openwisp/openwisp-fw/compile] Error 2
make[2]: Leaving directory `/home/borys/openwrt'
make[1]: *** [/home/borys/openwrt/staging_dir/target-i386_geode_uClibc-0.9.33.2/stamp/.package_compile] Error 2
make[1]: Leaving directory `/home/borys/openwrt'
make: ** [world] Erro 2

**Comment by nemesisdesign** [comment]
Which repository are you using exactly to compile?
Could you include the error of the verbose output?

**Comment by boryss** [comment]
Figured out the problem, turns out that i was missing OPENWISP_CONF. 
Thank you for the support

**Comment by nemesisdesign** [comment]
Another victim of #37 ;-)
