### ISSUE TITLE
Reduce size OpenWISP-Firmware

### ISSUE THREAD

**Issue by kietnlt** [openwisp/OpenWISP-Firmware#43]
Dear all,
I have problem when compile openwisp-firmware on openwrt, because the image is too large to install on device's flash. So I decide not to compile openvpn in openwisp by deleting openvpn-polarssl option in Makefile. I wonder if my new firmware is still working properly. Any idea help me reduce size of new openwisp-firmware.
Any help would be appreciated.
Thanks,
Kiet Nguyen.

**Comment by nemesisdesign** [comment]
@kietnlt We can't do this. I suggest you to use [openwisp2](https://github.com/openwisp/ansible-openwisp2) and its openwrt deamon ([openwisp-config](https://github.com/openwisp/openwisp-config)) which is smaller because does not require openvpn.
