### ISSUE TITLE
openwrt feed update give error

### ISSUE THREAD

**Issue by mastrus** [openwisp/OpenWISP-Firmware#44]
hi, i try the procedure for installing and compiling openwrt-firmware with these commands on ubuntu 12.04.5

```
git clone git://git.openwrt.org/openwrt.git
cd openwrt
cp feeds.conf.default feeds.conf
echo "src-git openwisp https://github.com/openwisp/OpenWISP-Firmware.git" >> feeds.conf
````
but after these commands:
```
./feed update 
```
i have these error:
```
Resolving deltas: 100% (126/126), done.
Create index file './feeds/openwisp.index' 
ERROR: please fix feeds/openwisp/meta/openwisp-fw/Makefile - see logs/feeds/openwisp/meta/openwisp-fw/dump.txt for details
Collecting package info: done
```
the dump of the log is:
```
~/openwrt$ tail ./logs/feeds/openwisp/meta/openwisp-fw/dump.txt 
Makefile:9: *** OPENWISP_CONF is not set.  Arresto.
```

**Comment by eballarini** [comment]
I'm experiencing the same issue on Ubuntu 16.04

**Comment by nemesisdesign** [comment]
You must declare `OPENWISP_CONF`.

See the last line of the error: `Makefile:9: *** OPENWISP_CONF is not set.`.

**Comment by eballarini** [comment]
my bash compilation script is:

make menuconfig
sudo make package/openwisp-fw/clean

export OPENWISP_CONF="http://127.0.1.1/eth0.tar.gz"
sudo make -j 1 V=s

but the variable is not set despite the export command

**Comment by nemesisdesign** [comment]
@eballarini, you should not compile with `sudo`. Do you get the same error if you compile without it?

**Comment by nemesisdesign** [comment]
@mastrus watch out, the repository to use for OpenWRT is now `https://github.com/openwrt/openwrt.git`.

**Comment by eballarini** [comment]
ok thanks, removing sudo did the job.
